/**
 * ============================================================================
 * THE SCHEMA CONTRACT — now derived from the real database
 * ============================================================================
 *
 * Through Build 05 this file was hand-transcribed from `supabase/migrations`
 * and carried a warning that it had never been checked against a running
 * PostgreSQL, because there was none to check against.
 *
 * That is over. `src/lib/supabase/database.types.ts` is generated by
 * `npm run db:types` from the hosted development project, after the migrations
 * were applied to it, and every name below is now an ALIAS into that file
 * rather than a second description of the same table.
 *
 * The distinction matters. A hand-written `ProductRow` can disagree with the
 * database and nothing notices until a query returns undefined at runtime. An
 * alias cannot: delete a column in a migration, regenerate, and every use of it
 * stops compiling. `npm run db:types:check` fails if this repository and the
 * database have drifted apart at all.
 *
 * What this file adds on top of the generated output is names that read like
 * the business rather than like the schema — `OrderRow` instead of
 * `Tables<"orders">`, `AdminRoleValue` instead of `Enums<"admin_role">` — and
 * nothing else. There are no invented shapes here.
 * ============================================================================
 */

import type { Database, Json } from "./database.types";

export type { Database, Json };

/* --------------------------------------------------------------- accessors */

type PublicSchema = Database["public"];

/** `Tables<"orders">` reads better than the full path at every call site. */
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];

/** The database's own functions, as the storefront and admin will call them. */
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T];

/* -------------------------------------------------------------- enum types */

export type CatalogueLifecycle = Enums<"catalogue_lifecycle">;
export type MediaRoleValue = Enums<"media_role">;
export type InventoryMovementKindValue = Enums<"inventory_movement_kind">;
export type OrderStateValue = Enums<"order_state">;
export type PaymentPreferenceValue = Enums<"payment_preference">;
export type PaymentMethodValue = Enums<"payment_method">;
export type PaymentStatusValue = Enums<"payment_status">;
export type OrderEventKindValue = Enums<"order_event_kind">;
export type ActorTypeValue = Enums<"actor_type">;
export type AdminRoleValue = Enums<"admin_role">;
export type SyncSourceValue = Enums<"sync_source">;
export type SyncDirectionValue = Enums<"sync_direction">;
export type SyncOperationValue = Enums<"sync_operation">;
export type SyncStatusValue = Enums<"sync_status">;
export type SyncConflictResolutionValue = Enums<"sync_conflict_resolution">;
export type AnalyticsEventKindValue = Enums<"analytics_event_kind">;

/* ------------------------------------------------------------ catalogue rows */

export type LocaleRow = Tables<"locales">;
export type PackTypeRow = Tables<"pack_types">;
export type SupplierRow = Tables<"suppliers">;
export type BrandRow = Tables<"brands">;
export type CategoryRow = Tables<"categories">;
export type MediaAssetRow = Tables<"media_assets">;
export type ProductFamilyRow = Tables<"product_families">;
export type ProductOptionAxisRow = Tables<"product_option_axes">;
export type ProductOptionValueRow = Tables<"product_option_values">;
export type ProductFamilyAxisRow = Tables<"product_family_axes">;
export type ProductRow = Tables<"products">;
export type ProductOptionAssignmentRow = Tables<"product_option_assignments">;
export type ProductMediaRow = Tables<"product_media">;
export type ProductContentRow = Tables<"product_content">;
export type CategoryContentRow = Tables<"category_content">;

/* ------------------------------------------------------------------- stock */

export type InventoryRow = Tables<"inventory">;
export type InventoryMovementRow = Tables<"inventory_movements">;

/* -------------------------------------------------------- people and places */

export type CustomerRow = Tables<"customers">;
export type CustomerAddressRow = Tables<"customer_addresses">;
export type DeliveryZoneRow = Tables<"delivery_zones">;

/* ---------------------------------------------------------------- commerce */

export type OrderRow = Tables<"orders">;
export type OrderItemRow = Tables<"order_items">;
export type OrderEventRow = Tables<"order_events">;

/* --------------------------------------------------------- staff and audit */

export type AdminProfileRow = Tables<"admin_profiles">;
export type AuditEventRow = Tables<"audit_events">;

/* --------------------------------------------- synchronisation and analytics */

export type SyncJobRow = Tables<"sync_jobs">;
export type SyncEventRow = Tables<"sync_events">;
export type SyncStateRow = Tables<"sync_state">;
export type SyncConflictRow = Tables<"sync_conflicts">;
export type AnalyticsEventRow = Tables<"analytics_events">;

/* ------------------------------------------------------------------- views */

/**
 * The public shelf: active, storefront-visible, and photographed. Note the
 * nullability — PostgreSQL cannot prove a column of a view is non-null, so the
 * generated types say `| null` where the underlying table says otherwise. That
 * is the database being honest about what it can guarantee, not a mistake.
 */
export type ProductShelfRow = Views<"product_shelf">;
export type InventoryLedgerCheckRow = Views<"inventory_ledger_check">;
